language: julia
sudo: required
dist: trusty
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false
env:
  - MPI_IMPL=mpich
  - MPI_IMPL=openmpi
before_install:
  - sh ./conf/travis-install-mpi.sh $MPI_IMPL
  - export PATH=$HOME/OpenMPI/bin:$HOME/MPICH/bin:$PATH
  - export CC=mpicc
  - export FC=mpif90
# Work around OpenMPI attempting to create overly long temporary
# file names - and erroring as a result
  - export TMPDIR=/tmp
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("MPI")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("MPI")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
