language: julia
sudo: required
dist: trusty
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
env:
  - MPI_IMPL=mpich
  - MPI_IMPL=openmpi
before_install:
  - sh ./conf/travis-install-mpi.sh $MPI_IMPL
  - export PATH=$HOME/OpenMPI/bin:$HOME/MPICH/bin:$PATH
  - export CC=mpicc
  - export FC=mpif90
# Work around OpenMPI attempting to create overly long temporary
# file names - and erroring as a result
  - export TMPDIR=/tmp
# Work around MacOS/OpenMPI issue:
#   https://github.com/open-mpi/ompi/issues/6518
#   https://github.com/open-mpi/ompi/issues/5798
  - export OMPI_MCA_btl=self,tcp
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("MPI")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("MPI")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - export DOCUMENTER_DEBUG="true"
        - julia --color=yes --project=docs/ -e 'using Pkg;
                                                      Pkg.instantiate();
                                                      Pkg.develop(PackageSpec(path=pwd()));
                                                      Pkg.build()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip